### ISSUE TITLE
After you run an analysis, editing the system removes the start analysis buttons, so you cannot run another one.  

### ISSUE THREAD

**Issue by sievers2501** [kdblocher/bridge#175]
I went to the site, and ran a fast analysis.  Then I started editing the system to run another run, but the start button for the analysis disappeared.  I tried refreshing to no avail.  

On a larger topic, we need to have a discussion of the GUI in general, but that is a much larger issue.

**Comment by kdblocher** [comment]
I was able to edit the system and run another analysis without issue.

Because the UI is so bad, it's possible that either the button was in a strange place or a step was missed, so here is exactly what I did:

System 1
1. Start with fresh app (delete editor data -> click "Reset Analysis DB" -> refresh screen)
2. Enter any system (I used `1C: 11-20 (C>D or 4333 or 3433)`)
3. Under "Analyses", click "Create"
4. Under the new analysis, click "Select"
5. Under "New analysis (1 paths)", click "Generate Deals"
6. Under "GenerateDeals", click "Start"
7. Under "New analysis (1 paths)", click "Satisfies"
8. Under "Satisfies", click "Start"
9. There should now be a 1C with ~20% near the bottom of the screen, with "Solve" to the right.

System 2
10. Edit the system (I added a line `1H: 11-20 5+H`)
11. Under "Analyses", click "Create" (below "Select" and "Remove" buttons from previous analysis)
12. Under the new analysis "New analysis (2 paths)", click "Select"
13. The previous solution should disappear, and you should now see "Generate Deals". Click it
14. Under "GenerateDeals", click "Start"
15. Under "New analysis (2 paths)", click "Satisfies"
16. Under "Satisfies", click "Start"

To verify both systems are independently accessible, you can click the "Select" buttons under "Analyses".

Feel free to close if you're able to follow this (or not if I made a mistake).

**Comment by sievers2501** [comment]
This seems to be working now.  Not sure what was going on.
